name: Deploy Spring Boot to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21' 

    - name: Build with Maven
      run: mvn clean package

    - name: Rename JAR for EB
      run: |
        mkdir bundle
        cp target/*.jar bundle/application.jar

    - name: Install AWS CLI & EB CLI
      run: |
        pip install --upgrade pip
        pip install awsebcli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize EB CLI
      run: |
        eb platform list --region ${{ secrets.AWS_REGION }}
        eb init ${{ secrets.EB_APP_NAME }} \
          --platform "corretto-21" \
          --region ${{ secrets.AWS_REGION }}
        eb use ${{ secrets.EB_ENV_NAME }}

    - name: Deploy JAR directly
      run: |
        cd bundle
        eb deploy --staged
