name: Deploy to Elastic Beanstalk
 
on:

  push:

    branches:

      - main
 
jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source

        uses: actions/checkout@v4

      - name: Setup Java

        uses: actions/setup-java@v4

        with:

          distribution: 'temurin'

          java-version: '21'

      - name: Build Project

        run: mvn clean install -DskipTests

      - name: Deploy to EB

        uses: einaregilsson/beanstalk-deploy@v21

        with:

          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}

          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          application_name: 'MyBeanstalkApp'

          environment_name: 'MyBeanstalkEnv'

          version_label: ${{ github.sha }}

          region: ${{ secrets.AWS_REGION }}

          deployment_package: target/springboot-example.jar
 
