name: CI-CD Pipeline for Spring Boot App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: target/*.jar

  deploy_to_aws:
    name: Deploy to AWS
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: java-app

    - name: Display structure of downloaded files
      run: ls -R

    - name: Deployment Step Placeholder
      run: echo "Artifact downloaded. Add AWS deployment commands here."
